FROM python:3.12-slim-bookworm

WORKDIR /app

# Set shell option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Update and upgrade
RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    apt-get install -y --no-install-recommends libgl1-mesa-glx libglib2.0-0 libmagic1 && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir uv

# エントリポイントスクリプトをコピー
COPY entrypoint-dev.sh /tmp/entrypoint.sh
# 実行権限を付与
RUN chmod +x /tmp/entrypoint.sh

# エントリポイントスクリプトを使用
ENTRYPOINT ["/tmp/entrypoint.sh"]