version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: "ext://sys.stdout"

loggers:
  app:
    handlers: ["default"]
    level: DEBUG
    propagate: false
  uvicorn.error:
    handlers: ["default"]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: ["default"]
    level: INFO
    propagate: false